name: Dispatch file diff

on:
  workflow_dispatch:
    inputs:
      file-path:
        description: first file to compare
        required: true
        type: string

jobs:
  diff_matrix:
    strategy:
      matrix:
        file:
          - resources/example.json
          - resources/other.json
    uses: ./.github/workflows/on_workflow_call_diff.yml
    with:
      file-path: ${{ matrix.file }}

  diff_files:
    runs-on: ubuntu-latest
    needs: diff_matrix
    steps:
      - name: Build Slack JSON
        id: construct_slack_message
        run: |
          blocks="[]"

          echo ${{ toJson(needs) }}
          echo ${{ toJson(needs.diff_matrix) }}

          for job in $(echo '${{ toJSON(needs) }}' | jq -r 'keys[]'); do
            file=$(echo '${{ toJSON(needs) }}' | jq -r ".\"$job\".outputs.file")
            diff=$(echo '${{ toJSON(needs) }}' | jq -r ".\"$job\".outputs.diff")

            if [ -n "$diff" ]; then
              block=$(jq -n \
                --arg f "$file" \
                --arg d "$diff" \
                '{type:"section", text:{type:"mrkdwn", text:("*" + $f + "*\n```" + $d + "```")}}')
              blocks=$(echo "$blocks" | jq ". + [$block]")
            fi
          done

          slack_message=$(jq -n --argjson blocks "$blocks" --arg pr "#files changed" '{text:"$pr", blocks:$blocks}')
          echo "$slack_message" >> GITHUB_OUTPUT

      - name: Send release info
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEB_HOOK }}
          webhook-type: incoming-webhook
          payload: |
            text: 'File Changed [${{ inputs.file-path }}]'
            attachments:
              - color: "#2c5f34"
                blocks: ${{ steps.construct_slack_message.outputs.slack_message }}
