name: Post Release Actions

on:
  release:
    types: [released]

jobs:
  test_action:
    name: "Test action being triggered by workflow release"
    runs-on: ubuntu-latest
    if: ${{ github.event.release.prerelease == false }}
    permissions:
      contents: read
    steps:
      - name: Extract release info
        id: release
        run: |
          max_body_len=2500
          body="${{ github.event.release.body }}"

          if [ "${#body}" -gt "$max_body_len" ]; then
            body="${body:0:$max_body_len}\n...*(truncated, see Github for full details)*"
          fi

          # Use jq to JSON-escape the body safely
          escaped=$(jq -Rn --arg text "$body" '$text')

          # escaped will look like: "line1\nline2\nline3"
          echo "body=$escaped" >> $GITHUB_OUTPUT
      - name: Send release info
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEB_HOOK }}
          webhook-type: incoming-webhook
          payload: |
            text: 'New Release [${{ github.event.release.name }}]'
            attachments:
              - color: "#2c5f34"
                blocks:
                - type: section
                  text:
                    type: mrkdwn
                    text: |-
                      *<${{ github.event.release.html_url }}|See here for details>*
                - type: section
                  text: 
                    type: mrkdwn
                    text: ${{ steps.release.outputs.body }}
