name: Post Release Actions

on:
  release:
    types: [published]

jobs:
  test_action:
    name: "Test action being triggered by workflow release"
    runs-on: ubuntu-latest
    if: ${{ github.event.release.prerelease == false }}
    permissions:
      contents: read
    steps:
      - name: Extract release info
        id: release
        run: |
          formatted=$(echo "${${{ github.event.release.body }}//$'\n'/'%0A'}")
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$formatted" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Send release info
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEB_HOOK }}
          webhook-type: incoming-webhook
          payload: |
            text: 'New Release [${{ github.event.release.name }}]'
            attachments:
              - color: "#2c5f34"
                blocks:
                - type: section
                  text:
                    type: mrkdwn
                    text: |-
                      *<${{ github.event.release.html_url }}|See here for details>*
                - type: section
                  text: 
                    type: plain_text
                    text: "${{ steps.release.outputs.body }}"
