name: Releases

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          allowUpdates: true
          prelease: false
          skipIfReleaseExists: false
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          generateReleaseNotes: true
